env:
  es2021: true
  node: true
  jest: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  prefer-destructuring: 0
  no-console: 0
  no-restricted-syntax: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
