name: nodejs
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v3

      - name: install
        run: make install

      - name: run linter
        run: make lint
      
      - name: run tests
        run: make test

      - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v5.0.0
        # Add Code Climate secret key
        env:
          # CC_TEST_REPORTER_ID: 6f44c41dc4945c09cde7ea336049afa6f6925d5e826b7e0a031c2c0eab79f5d0
          CC_TEST_REPORTER_ID: ${{ REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true